# Generated by Django 3.2.6 on 2021-11-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'commune',
                'verbose_name_plural': 'COMMUNES',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Concessionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('contacts', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('site_internet', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'concessionaire',
                'verbose_name_plural': 'CONCESSIONNAIRES',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'villes',
                'verbose_name_plural': 'VILLES',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('type_equipement', models.CharField(choices=[('FO_CUIVRE', 'FO/PAIRES DE CUIVRE'), ('FO', 'FO')], default='CUIVRE', max_length=50)),
                ('profondeur_cable', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=12, null=True)),
                ('dtce_chambre_proche', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chbre_proche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locale_proches', to='chambres.locale')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.commune')),
                ('concessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.concessionaire')),
            ],
            options={
                'verbose_name': 'chambre technique',
                'verbose_name_plural': 'CHAMBRES TECHNIQUES',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.ville'),
        ),
    ]
