# Generated by Django 3.1.7 on 2021-11-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0005_auto_20211117_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locale',
            name='user',
        ),
    ]
